ENCODING="ISO-8859-15"
DATAPATH="`pwd`/$1"
cd $1

echo "DEST.TMI
LINE.TMI
CONAREA.TMI
CONFINREL.TMI
USRSTAR.TMI
USRSTOP.TMI
POINT.TMI
TILI.TMI
LINK.TMI
POOL.TMI
JOPA.TMI
JOPATILI.TMI
ORUN.TMI
ORUNORUN.TMI
SPECDAY.TMI
PEGR.TMI
EXCOPDAY.TMI
PEGRVAL.TMI
TIVE.TMI
TIMDEMGRP.TMI
TIMDEMRNT.TMI
PUJO.TMI" | while read i; do
	TABLE=`basename $i .TMI`
	echo "COPY ${TABLE} FROM '${DATAPATH}/${i}' WITH DELIMITER AS '|' NULL AS '' CSV ENCODING '${ENCODING}';"
done
