ENCODING="UTF-8"
DATAPATH="`pwd`/$1"
cd $1

echo "DESTXXXXXX.TMI
LINEXXXXXX.TMI
CONFINREL.TMI
CONAREAXXX.TMI
USRSTARXXX.TMI
USRSTOPXXX.TMI
POINTXXXXX.TMI
TILIXXXXXX.TMI
LINKXXXXXX.TMI
POOLXXXXXX.TMI
JOPAXXXXXX.TMI
JOPATILIXX.TMI
ORUNXXXXXX.TMI
ORUNORUNXX.TMI
SPECDAYXXX.TMI
PEGRXXXXXX.TMI
EXCOPDAYXX.TMI
PEGRVALXXX.TMI
TIVEXXXXXX.TMI
TIMDEMGRPX.TMI
TIMDEMRNTX.TMI
PUJOXXXXXX.TMI
SCHEDVERSX.TMI
PUJOPASSXX.TMI
OPERDAYXXX.TMI" | while read i; do
	TABLE=`basename $i .TMI | sed 's/X//g'`
	echo "COPY ${TABLE} FROM '${DATAPATH}/${i}' WITH DELIMITER AS '|' NULL AS '' CSV ENCODING '${ENCODING}';"
done
