ENCODING="ISO-8859-15"
DATAPATH="`pwd`/$1"
cd $1

echo "DESTXXXXXX.TMI
LINEXXXXXX.TMI
CONAREAXXX.TMI
CONFINRELX.TMI
USRSTARXXX.TMI
USRSTOPXXX.TMI
POINTXXXXX.TMI
TILIXXXXXX.TMI
LINKXXXXXX.TMI
POOLXXXXXX.TMI
JOPAXXXXXX.TMI
JOPATILIXX.TMI
ORUNXXXXXX.TMI
SCHEDVERSX.TMI
PUJOPASSXX.TMI
OPERDAYXXX.TMI" | while read i; do
	TABLE=`basename $i .TMI | sed 's/X//g'`
	echo "COPY ${TABLE} FROM '${DATAPATH}/${i}' WITH DELIMITER AS '|' NULL AS '' CSV ENCODING '${ENCODING}';"
done
